apiVersion: v1
kind: Service
metadata:
  name: http-echo-svc
  labels:
    run: http-echo
spec:
  ports:
  - port: 80
    targetPort: 5678  
    protocol: TCP
  selector:
    run: http-echo
  type: NodePort