apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  template:
    spec:
      containers:
        - name: http-echo
          args:
            - "-text=hello Production environment"
